import { z } from 'zod';
import { STATUSES, WEBHOOK_EVENT_TYPES, type Status, type WebhookEventType } from '@flux/shared';

// Input enums
export const statusSchema = z.enum(STATUSES as [Status, ...Status[]]);
export const webhookEventSchema = z.enum(WEBHOOK_EVENT_TYPES as [WebhookEventType, ...WebhookEventType[]]);

// Guardrail as accepted on input (id is generated by the store)
export const guardrailInputSchema = z.object({
  number: z.number().int().positive().describe('Priority number (higher = more critical, e.g., 999, 9999)'),
  text: z.string().describe('Guardrail instruction'),
});

// ============ Output schemas ============
// Deliberately loose (core fields + passthrough) so structured output
// validation never fights the storage layer over optional fields.

export const guardrailSchema = z
  .object({ number: z.number(), text: z.string() })
  .passthrough();

export const commentSchema = z
  .object({
    id: z.string(),
    body: z.string(),
    author: z.string(),
    created_at: z.string(),
  })
  .passthrough();

export const projectStatsSchema = z
  .object({ total: z.number(), done: z.number() })
  .passthrough();

export const projectSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    description: z.string().optional(),
    stats: projectStatsSchema.optional(),
  })
  .passthrough();

export const epicSchema = z
  .object({
    id: z.string(),
    title: z.string(),
    status: z.string(),
    project_id: z.string(),
    depends_on: z.array(z.string()).optional(),
    notes: z.string().optional(),
    auto: z.boolean().optional(),
  })
  .passthrough();

export const taskSchema = z
  .object({
    id: z.string(),
    title: z.string(),
    status: z.string(),
    project_id: z.string(),
    depends_on: z.array(z.string()).optional(),
    epic_id: z.string().optional(),
    priority: z.number().optional(),
    blocked: z.boolean().optional(),
    blocked_reason: z.string().optional(),
    acceptance_criteria: z.array(z.string()).optional(),
    guardrails: z.array(guardrailSchema).optional(),
    comments: z.array(commentSchema).optional(),
    workers: z.array(z.string()).optional(),
  })
  .passthrough();

export const webhookSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    url: z.string(),
    events: z.array(z.string()),
    enabled: z.boolean().optional(),
    project_id: z.string().optional(),
  })
  .passthrough();

export const webhookDeliverySchema = z.object({ id: z.string() }).passthrough();

export const blobMetadataSchema = z
  .object({
    id: z.string(),
    filename: z.string(),
    mime_type: z.string(),
    size: z.number(),
    task_id: z.string().optional(),
    created_at: z.string().optional(),
  })
  .passthrough();
